# ===================================
# GROQ - LLM (chat)
# ===================================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# ===================================
# OLLAMA - EMBEDDINGS (LOCAL, FREE)
# ===================================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.vectorstore.chroma.embedding-client=ollama
spring.ai.openai.embedding.enabled=false

# ===================================
# CHROMA - VECTOR DB
# ===================================
spring.ai.vectorstore.chroma.host=localhost
spring.ai.vectorstore.chroma.port=8000
spring.ai.vectorstore.chroma.collection-name=company-docs
spring.ai.vectorstore.chroma.initialize-schema=true


# ===================================
# UPLOAD
# ===================================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# ===================================
# LOGGING
# ===================================
logging.level.org.springframework.ai=DEBUG